// apps/api/resources/js/Components/DefinitionList.tsx
import React from 'react';

import { css } from '@style/css';

export type DefinitionListProps = {
  items: Array<[string, string]>;
};

export function DefinitionList({ items }: DefinitionListProps) {
  return (
    <dl>
      {items.map(([label, text]) => {
        return (
          <React.Fragment key={label}>
            <dt
              className={css({
                fontWeight: 'bold',
                fontSize: 'sm',
                color: 'gray.600',
              })}
            >
              {label}
            </dt>
            <dd
              className={css({
                mb: '3',
                '&:last-child': {
                  mb: 0,
                },
              })}
            >
              {text}
            </dd>
          </React.Fragment>
        );
      })}
    </dl>
  );
}

// apps/api/resources/js/Components/DefinitionList.vue
<script setup lang="ts">
import { css } from '@style/css';

const props = defineProps<{
  items: Array<[string, string]>;
}>();
</script>

<template>
  <dl>
    <template v-for="[label, text] of props.items" :key="label">
      <dt
        :class="
          css({
            fontWeight: 'bold',
            fontSize: 'sm',
            color: 'gray.600',
          })
        "
      >
        {{ label }}
      </dt>
      <dd
        :class="
          css({
            mb: '3',
            '&:last-child': {
              mb: 0,
            },
          })
        "
      >
        {{ text }}
      </dd>
    </template>
  </dl>
</template>
