// apps/api/resources/js/Components/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue';
import { ChevronLeftIcon, ChevronRightIcon } from 'lucide-vue-next';
import { hstack } from '@style/patterns';

import AppButton from './AppButton.vue';

const props = withDefaults(
  defineProps<{
    as?: string;
    baseUrl: string;
    currentPage: number;
    lastPage: number;
  }>(),
  { as: 'div' },
);

const isPreviousNavigationDisabled = computed(() => props.currentPage === 1);
const isNextNavigationDisabled = computed(() => props.currentPage === props.lastPage);
</script>

<template>
  <component :is="props.as" :class="hstack({ w: 'fit-content' })">
    <AppButton btnSize="sm" :disabled="isPreviousNavigationDisabled" :href="`${baseUrl}?page=1`">
      Début de liste
    </AppButton>
    <AppButton
      btnSize="sm"
      :disabled="isPreviousNavigationDisabled"
      :href="`${baseUrl}?page=${currentPage - 1}`"
    >
      <template #left-icon>
        <ChevronLeftIcon :size="20" />
      </template>
      Page précédente
    </AppButton>

    <AppButton
      btnSize="sm"
      :disabled="isNextNavigationDisabled"
      :href="`${baseUrl}?page=${currentPage + 1}`"
    >
      <template #right-icon>
        <ChevronRightIcon :size="20" />
      </template>
      Page suivante
    </AppButton>
    <AppButton
      btnSize="sm"
      :disabled="isNextNavigationDisabled"
      :href="`${baseUrl}?page=${lastPage}`"
    >
      Fin de liste
    </AppButton>
  </component>
</template>

// apps/api/resources/js/Components/Pagination.tsx
import React from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';

import { hstack } from '@style/patterns';

import { Button } from './Button';

export type PaginationProps = {
  baseUrl: string;
  currentPage: number;
  lastPage: number;
  as?: React.ElementType;
};

export function Pagination({ baseUrl, currentPage, lastPage, as = 'div' }: PaginationProps) {
  const isPreviousNavigationDisabled = currentPage === 1;
  const isNextNavigationDisabled = currentPage === lastPage;

  const Root = as;

  return (
    <Root className={hstack({ w: 'fit-content' })}>
      <Button.Link btnSize="sm" disabled={isPreviousNavigationDisabled} href={`${baseUrl}?page=1`}>
        Début de liste
      </Button.Link>
      <Button.Link
        btnSize="sm"
        disabled={isPreviousNavigationDisabled}
        href={`${baseUrl}?page=${currentPage - 1}`}
        leftIcon={<ChevronLeft size={20} />}
      >
        Page précédente
      </Button.Link>

      <Button.Link
        btnSize="sm"
        disabled={isNextNavigationDisabled}
        href={`${baseUrl}?page=${currentPage + 1}`}
        rightIcon={<ChevronRight size={20} />}
      >
        Page suivante
      </Button.Link>
      <Button.Link
        btnSize="sm"
        disabled={isNextNavigationDisabled}
        href={`${baseUrl}?page=${lastPage}`}
      >
        Fin de liste
      </Button.Link>
    </Root>
  );
}
