// apps/api/resources/js/Pages/Layout.vue
<script setup lang="ts">
import { usePage } from '@inertiajs/vue3';
import { computed } from 'vue';

import { css } from '@style/css';

import AppNavbar from '~/Components/AppNavbar.vue';

const page = usePage();
const isLoggedIn = computed(() => page.props.user !== null);
</script>

<template>
  <AppNavbar v-if="isLoggedIn" />
  <div
    scroll-region="true"
    :class="
      css({
        w: 'full',
        h: 'full',
        overflowY: 'auto',
      })
    "
  >
    <main
      :class="
        css({
          p: '4',
          px: '8',
          width: 'full',
          minHeight: 'full',
          mx: 'auto',
        })
      "
    >
      <slot />
    </main>
  </div>
</template>

// apps/api/resources/js/Pages/Layout.tsx
import React, { PropsWithChildren } from 'react';

import { Navbar } from '~/Components';
import { css } from '@style/css';
import { usePage } from '@inertiajs/inertia-react';

type LayoutProps = PropsWithChildren<{}>;

export function Layout({ children }: LayoutProps) {
  const { props } = usePage();
  const isLoggedIn = props.user !== null;

  return (
    <>
      {isLoggedIn && <Navbar />}
      <div
        scroll-region="true"
        className={css({
          w: 'full',
          h: 'full',
          overflowY: 'auto',
        })}
      >
        <main
          className={css({
            p: '4',
            px: '8',
            width: 'full',
            minHeight: 'full',
            mx: 'auto',
          })}
        >
          {children}
        </main>
      </div>
    </>
  );
}
