// apps/api/resources/js/Pages/Admin/Login.tsx
import React, { useState } from 'react';
import { useForm, usePage } from '@inertiajs/inertia-react';

import { FieldContainer, TextInput, Button, Message } from '~/Components';
import { Layout } from '~/Pages/Layout';
import { css } from '@style/css';
import { vstack } from '@style/patterns';

export default function Login() {
  const { props } = usePage();
  const { data, setData, post, processing } = useForm({
    username: '',
    password: '',
  });
  const [hiddenErrors, setHiddenErrors] = useState<string[]>([]);

  function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    post('/admin/login', {
      onFinish: () => setHiddenErrors([]),
    });
  }

  return (
    <div
      className={vstack({
        justifyContent: 'center',
        alignItems: 'center',
      })}
    >
      {!hiddenErrors.includes('login') && props?.errors?.login && (
        <Message kind="error" onClose={() => setHiddenErrors((errors) => [...errors, 'login'])}>
          Mot de passe ou utilisateur incorrect
        </Message>
      )}
      <form
        onSubmit={submit}
        className={vstack({
          justifyContent: 'center',
          alignItems: 'flex-start',
          gap: 3,
        })}
      >
        <FieldContainer>
          <label className={css({ textStyle: 'label' })} htmlFor="username">
            Nom d'utilisateur
          </label>
          <TextInput
            type="text"
            name="username"
            id="email"
            required
            value={data.username}
            onChange={(e) => setData('username', e.target.value)}
          />
        </FieldContainer>

        <FieldContainer>
          <label className={css({ textStyle: 'label' })} htmlFor="password">
            Mot de passe
          </label>
          <TextInput
            type="password"
            name="password"
            id="password"
            required
            value={data.password}
            onChange={(e) => setData('password', e.target.value)}
          />
        </FieldContainer>

        <FieldContainer alignment="center">
          <Button.Base disabled={processing}>Se connecter</Button.Base>
        </FieldContainer>
      </form>
    </div>
  );
}

Login.layout = (page: JSX.Element) => <Layout children={page} />;

// apps/api/resources/js/Pages/Admin/Login.vue
<script lang="ts">
import AppLayout from '~/Pages/Layout.vue';
import FieldContainer from '~/Components/FieldContainer.vue';
import TextInput from '~/Components/TextInput.vue';
import AppButton from '~/Components/AppButton.vue';
import AppMessage from '~/Components/AppMessage.vue';

export default {
  layout: AppLayout,
};
</script>

<script setup lang="ts">
import { computed, ref } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import { css } from '@style/css';
import { vstack } from '@style/patterns';

const page = usePage();
const form = useForm({
  username: '',
  password: '',
});
const hiddenErrors = ref<string[]>([]);

const shouldDisplayErrorMessage = computed(() => {
  return !hiddenErrors.value.includes('login') && Boolean(page?.props?.errors?.login);
});

function submit(e: SubmitEvent) {
  e.preventDefault();
  form.post('/admin/login', {
    onFinish: () => {
      hiddenErrors.value = [];
    },
  });
}
</script>

<template>
  <div
    :class="
      vstack({
        justifyContent: 'center',
        alignItems: 'center',
      })
    "
  >
    <AppMessage
      v-if="shouldDisplayErrorMessage"
      kind="error"
      @close="() => (hiddenErrors = [...hiddenErrors, 'login'])"
    >
      Mot de passe ou utilisateur incorrect
    </AppMessage>
    <form
      @submit="submit"
      :class="
        vstack({
          justifyContent: 'center',
          alignItems: 'flex-start',
          gap: 3,
        })
      "
    >
      <FieldContainer>
        <label :class="css({ textStyle: 'label' })" for="username"> Nom d'utilisateur </label>
        <TextInput type="text" name="username" id="email" required v-model="form.username" />
      </FieldContainer>

      <FieldContainer>
        <label :class="css({ textStyle: 'label' })" for="password"> Mot de passe </label>
        <TextInput type="password" name="password" id="password" required v-model="form.password" />
      </FieldContainer>

      <FieldContainer alignment="center">
        <AppButton :disabled="form.processing">Se connecter</AppButton>
      </FieldContainer>
    </form>
  </div>
</template>
