// apps/api/resources/js/Pages/Admin/Posts/Index.tsx
import React from 'react';
import {
  createColumnHelper,
  useReactTable,
  getCoreRowModel,
  flexRender,
} from '@tanstack/react-table';
import { DateTime } from 'luxon';

import { AdminPostsData } from '@weakassdev/shared/validators';

import { css } from '@style/css';
import { Layout } from '~/Pages/Layout';
import { Table, Button } from '~/Components';

const columnHelpers = createColumnHelper<AdminPostsData['data'][number]>();
const columns = [
  columnHelpers.accessor('id', {
    header: () => 'Identifiant',
    cell: (info) => info.getValue().slice(30),
  }),
  columnHelpers.accessor('author.username', {
    header: () => 'Auteur(e)',
    cell: (info) => (
      <Table.CellLink info={info.getValue()} href={`/admin/users/${info.row.original.author.id}`} />
    ),
  }),
  columnHelpers.accessor('status', {
    header: () => 'Statut',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('revisions', {
    header: () => 'Révisions',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('content.content', {
    header: () => 'Contenu',
    cell: (info) => (
      <span
        className={css({
          display: 'inline-block',
          overflow: 'hidden',
          whiteSpace: 'nowrap',
          maxWidth: '300px',
          textOverflow: 'ellipsis',
          wordBreak: 'break-all',
        })}
      >
        {info.getValue()}
      </span>
    ),
  }),
  columnHelpers.accessor('createdAt', {
    header: () => 'Posté le',
    cell: (info) => DateTime.fromISO(info.getValue()).toLocaleString(DateTime.DATETIME_MED),
  }),
  columnHelpers.display({
    id: 'actions',
    header: () => 'Actions',
    cell: (info) => (
      <div>
        <Button.Link href={`/admin/posts/${info.row.getValue('id')}`} btnSize="sm">
          Détails
        </Button.Link>
      </div>
    ),
  }),
];

type IndexProps = {
  posts: AdminPostsData;
};

export default function Index({ posts }: IndexProps) {
  const { data, meta } = posts;
  const table = useReactTable({
    data: data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  return (
    <>
      <h1 className={css({ textStyle: 'h2', mb: '10' })}>Posts</h1>
      <Table.Root>
        <Table.Container>
          <Table.Header>
            {table.getHeaderGroups().map((headerGroup) => (
              <tr key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <th key={header.id}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </th>
                ))}
              </tr>
            ))}
          </Table.Header>
          <Table.Body>
            {table.getRowModel().rows.map((row) => (
              <tr key={row.id}>
                {row.getVisibleCells().map((cell) => (
                  <td key={cell.id}>{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>
                ))}
              </tr>
            ))}
          </Table.Body>
          <Table.Footer length={columns.length}>
            <Table.Pagination
              baseUrl="/admin/posts"
              currentPage={meta.currentPage}
              lastPage={meta.lastPage}
            />
          </Table.Footer>
        </Table.Container>
      </Table.Root>
    </>
  );
}

Index.layout = (page: JSX.Element) => <Layout children={page} />;

// apps/api/resources/js/Pages/Admin/Posts/Index.vue
<script lang="ts">
import AppLayout from '~/Pages/Layout.vue';
import AppButton from '~/Components/AppButton.vue';

export default {
  layout: AppLayout,
};
</script>

<script setup lang="ts">
import { DateTime } from 'luxon';
import { createColumnHelper, useVueTable, FlexRender, getCoreRowModel } from '@tanstack/vue-table';
import { css } from '@style/css';

import { AdminPostsData } from '@weakassdev/shared/validators';

import TableRoot from '~/Components/Table/TableRoot.vue';
import TableHeader from '~/Components/Table/TableHeader.vue';
import TableBody from '~/Components/Table/TableBody.vue';
import TableContainer from '~/Components/Table/TableContainer.vue';
import TableFooter from '~/Components/Table/TableFooter.vue';
import TableCellLink from '~/Components/Table/TableCellLink.vue';
import Pagination from '~/Components/Pagination.vue';

const props = defineProps<{
  posts: AdminPostsData;
}>();

const columnHelpers = createColumnHelper<AdminPostsData['data'][number]>();

const columns = [
  columnHelpers.accessor('id', {
    header: () => 'Identifiant',
    cell: (info) => info.getValue().slice(30),
  }),
  columnHelpers.accessor('author.username', {
    header: () => 'Auteur(e)',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('status', {
    header: () => 'Statut',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('revisions', {
    header: () => 'Révisions',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('content.content', {
    header: () => 'Contenu',
    cell: (info) => info.getValue(),
  }),
  columnHelpers.accessor('createdAt', {
    header: () => 'Posté le',
    cell: (info) => DateTime.fromISO(info.getValue()).toLocaleString(DateTime.DATETIME_MED),
  }),
  columnHelpers.display({
    id: 'actions',
    header: () => 'Actions',
    cell: (info) => 'Hey',
    // <div>
    //   <Button.Link href={`/admin/posts/${info.row.getValue('id')}`} btnSize="sm">
    //     Détails
    //   </Button.Link>
    // </div>
  }),
];

const table = useVueTable({
  get data() {
    return props.posts.data;
  },
  columns,
  getCoreRowModel: getCoreRowModel(),
});
</script>

<template>
  <h1 :class="css({ textStyle: 'h2', mb: '10' })">Posts</h1>
  <TableRoot>
    <TableContainer>
      <TableHeader>
        <tr v-for="headerGroup of table.getHeaderGroups()" :key="headerGroup.id">
          <th v-for="header of headerGroup.headers" :key="header.id">
            <FlexRender
              v-if="!header.isPlaceholder"
              :render="header.column.columnDef.header"
              :props="header.getContext()"
            />
          </th>
        </tr>
      </TableHeader>

      <TableBody>
        <tr v-for="row of table.getRowModel().rows" :key="row.id">
          <td v-for="cell of row.getVisibleCells()" :key="cell.id">
            <TableCellLink
              v-if="cell.column.id === 'author_username'"
              :info="cell.row.original.author.username"
              :href="`/admin/users/${cell.row.original.author.id}`"
            />
            <span
              v-else-if="cell.column.id === 'content_content'"
              :class="
                css({
                  display: 'inline-block',
                  overflow: 'hidden',
                  whiteSpace: 'nowrap',
                  maxWidth: '300px',
                  textOverflow: 'ellipsis',
                  wordBreak: 'break-all',
                })
              "
            >
              {{ row.getValue('content_content') }}
            </span>

            <div v-else-if="cell.column.id === 'actions'">
              <AppButton :href="`/admin/posts/${row.getValue('id')}`" btnSize="sm">
                Détails
              </AppButton>
            </div>

            <FlexRender v-else :render="cell.column.columnDef.cell" :props="cell.getContext()" />
          </td>
        </tr>
      </TableBody>

      <TableFooter :length="columns.length">
        <Pagination
          as="span"
          baseUrl="/admin/posts"
          :currentPage="props.posts.meta.currentPage"
          :lastPage="props.posts.meta.lastPage"
        />
      </TableFooter>
    </TableContainer>
  </TableRoot>
</template>
